# This file has been generated by node2nix 1.1.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-2.1.5" = {
      name = "async";
      packageName = "async";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.1.5.tgz";
        sha1 = "e587c68580994ac67fc56ff86d3ac56bdbe810bc";
      };
    };
    "ltx-2.7.1" = {
      name = "ltx";
      packageName = "ltx";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ltx/-/ltx-2.7.1.tgz";
        sha1 = "0e5cbdcb5bf178cfa7831ea41dc323d97422315a";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "node-xmpp-core-5.0.9" = {
      name = "node-xmpp-core";
      packageName = "node-xmpp-core";
      version = "5.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-core/-/node-xmpp-core-5.0.9.tgz";
        sha1 = "5c28c28edb1fb3f8beba2c6760777613f48f342a";
      };
    };
    "toobusy-js-0.5.1" = {
      name = "toobusy-js";
      packageName = "toobusy-js";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toobusy-js/-/toobusy-js-0.5.1.tgz";
        sha1 = "5511f78f6a87a6a512d44fdb0efa13672217f659";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "debug-2.6.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.3.tgz";
        sha1 = "0f7eb8c30965ec08c72accfa0130c8b79984141d";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "reconnect-core-https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged" = {
      name = "reconnect-core";
      packageName = "reconnect-core";
      version = "0.0.1";
      src = fetchurl {
        name = "reconnect-core-0.0.1.tar.gz";
        url = https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged;
        sha256 = "431dd7a1578061815270e4ad59c6e8b40dff6b308244973e1c11049ccbf1629b";
      };
    };
    "node-xmpp-tls-connect-1.0.1" = {
      name = "node-xmpp-tls-connect";
      packageName = "node-xmpp-tls-connect";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-tls-connect/-/node-xmpp-tls-connect-1.0.1.tgz";
        sha1 = "91ace43ac26b138861b2be478df9df19d61dc5c3";
      };
    };
    "@xmpp/jid-0.0.2" = {
      name = "@xmpp/jid";
      packageName = "@xmpp/jid";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/jid/-/jid-0.0.2.tgz";
        sha1 = "0d528ca9d58dafc833665564ffe62f332a3167f2";
      };
    };
    "@xmpp/streamparser-0.0.6" = {
      name = "@xmpp/streamparser";
      packageName = "@xmpp/streamparser";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/streamparser/-/streamparser-0.0.6.tgz";
        sha1 = "118033ea9db7c86a1cb46103f269ebff79f6f1ea";
      };
    };
    "@xmpp/xml-0.1.3" = {
      name = "@xmpp/xml";
      packageName = "@xmpp/xml";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/xml/-/xml-0.1.3.tgz";
        sha1 = "1f14399e53e419688558698f6c62e71e39a86a6e";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "backoff-2.3.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.3.0.tgz";
        sha1 = "ee7c7e38093f92e472859db635e7652454fc21ea";
      };
    };
  };
  args = {
    name = "node-xmpp-joap";
    packageName = "node-xmpp-joap";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      (sources."async-2.1.5" // {
        dependencies = [
          sources."lodash-4.17.4"
        ];
      })
      (sources."ltx-2.7.1" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."node-uuid-1.4.8"
      (sources."node-xmpp-core-5.0.9" // {
        dependencies = [
          (sources."debug-2.6.3" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."inherits-2.0.3"
          sources."lodash.assign-4.2.0"
          (sources."reconnect-core-https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged" // {
            dependencies = [
              sources."backoff-2.3.0"
            ];
          })
          sources."node-xmpp-tls-connect-1.0.1"
          sources."@xmpp/jid-0.0.2"
          sources."@xmpp/streamparser-0.0.6"
          sources."@xmpp/xml-0.1.3"
        ];
      })
      sources."toobusy-js-0.5.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Jabber Object Access Protocol (XEP-0075) library for node-xmpp";
      homepage = http://github.com/flosse/node-xmpp-joap;
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}