# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-2.1.2" = {
      name = "async";
      packageName = "async";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.1.2.tgz";
        sha1 = "612a4ab45ef42a70cde806bad86ee6db047e8385";
      };
    };
    "ltx-2.5.1" = {
      name = "ltx";
      packageName = "ltx";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ltx/-/ltx-2.5.1.tgz";
        sha1 = "f583f622097d2f161d245a0fc43b8d2ee3116758";
      };
    };
    "node-expat-2.3.15" = {
      name = "node-expat";
      packageName = "node-expat";
      version = "2.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-expat/-/node-expat-2.3.15.tgz";
        sha1 = "96a53a0bc00649daf78f4fc074a23e644c223b4c";
      };
    };
    "node-stringprep-0.8.0" = {
      name = "node-stringprep";
      packageName = "node-stringprep";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-stringprep/-/node-stringprep-0.8.0.tgz";
        sha1 = "e4a39e48ea4486ec454bc08dca51dd1aa4686417";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "node-xmpp-core-5.0.4" = {
      name = "node-xmpp-core";
      packageName = "node-xmpp-core";
      version = "5.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-core/-/node-xmpp-core-5.0.4.tgz";
        sha1 = "9fb557b48484c573d99788382d8dea768e47d1c7";
      };
    };
    "toobusy-js-0.5.1" = {
      name = "toobusy-js";
      packageName = "toobusy-js";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toobusy-js/-/toobusy-js-0.5.1.tgz";
        sha1 = "5511f78f6a87a6a512d44fdb0efa13672217f659";
      };
    };
    "lodash-4.16.6" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.16.6.tgz";
        sha1 = "d22c9ac660288f3843e16ba7d2b5d06cca27d777";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "bindings-1.2.1" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz";
        sha1 = "14ad6113812d2d37d72e67b4cacb4bb726505f11";
      };
    };
    "nan-2.4.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.4.0.tgz";
        sha1 = "fb3c59d45fe4effe215f0b890f8adf6eb32d2232";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "nan-2.3.5" = {
      name = "nan";
      packageName = "nan";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.3.5.tgz";
        sha1 = "822a0dc266290ce4cd3a12282ca3e7e364668a08";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "debug-2.3.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.3.0.tgz";
        sha1 = "3912dc55d7167fc3af17d2b85c13f93deaedaa43";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "reconnect-core-https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged" = {
      name = "reconnect-core";
      packageName = "reconnect-core";
      version = "0.0.1";
      src = fetchurl {
        name = "reconnect-core-0.0.1.tar.gz";
        url = https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged;
        sha256 = "431dd7a1578061815270e4ad59c6e8b40dff6b308244973e1c11049ccbf1629b";
      };
    };
    "node-xmpp-tls-connect-1.0.1" = {
      name = "node-xmpp-tls-connect";
      packageName = "node-xmpp-tls-connect";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-xmpp-tls-connect/-/node-xmpp-tls-connect-1.0.1.tgz";
        sha1 = "91ace43ac26b138861b2be478df9df19d61dc5c3";
      };
    };
    "@xmpp/jid-0.0.1" = {
      name = "@xmpp/jid";
      packageName = "@xmpp/jid";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/jid/-/jid-0.0.1.tgz";
        sha1 = "c82c3cb6d7fd76637f2f97aec2e0c68942aab0a1";
      };
    };
    "@xmpp/streamparser-0.0.1" = {
      name = "@xmpp/streamparser";
      packageName = "@xmpp/streamparser";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/streamparser/-/streamparser-0.0.1.tgz";
        sha1 = "2d55d61a315f78a615a3dbb0b4509f190635b0cf";
      };
    };
    "@xmpp/xml-0.0.1" = {
      name = "@xmpp/xml";
      packageName = "@xmpp/xml";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmpp/xml/-/xml-0.0.1.tgz";
        sha1 = "2e4e10eabbd3f77bf5e5356a53f231293c81b002";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "backoff-2.3.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.3.0.tgz";
        sha1 = "ee7c7e38093f92e472859db635e7652454fc21ea";
      };
    };
  };
  args = {
    name = "node-xmpp-joap";
    packageName = "node-xmpp-joap";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      (sources."async-2.1.2" // {
        dependencies = [
          sources."lodash-4.16.6"
        ];
      })
      (sources."ltx-2.5.1" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      (sources."node-expat-2.3.15" // {
        dependencies = [
          sources."bindings-1.2.1"
          sources."nan-2.4.0"
        ];
      })
      (sources."node-stringprep-0.8.0" // {
        dependencies = [
          sources."bindings-1.2.1"
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          sources."nan-2.3.5"
        ];
      })
      sources."node-uuid-1.4.7"
      (sources."node-xmpp-core-5.0.4" // {
        dependencies = [
          (sources."debug-2.3.0" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."inherits-2.0.3"
          sources."lodash.assign-4.2.0"
          (sources."reconnect-core-https://codeload.github.com/dodo/reconnect-core/legacy.tar.gz/merged" // {
            dependencies = [
              sources."backoff-2.3.0"
            ];
          })
          sources."node-xmpp-tls-connect-1.0.1"
          sources."@xmpp/jid-0.0.1"
          sources."@xmpp/streamparser-0.0.1"
          sources."@xmpp/xml-0.0.1"
        ];
      })
      sources."toobusy-js-0.5.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Jabber Object Access Protocol (XEP-0075) library for node-xmpp";
      homepage = http://github.com/flosse/node-xmpp-joap;
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}